### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by tecufanujacu** [ArthurPatriot/upwork-rss-informer#1]
I have just tried your application with some rss source and I have some doubt:

- if I stop the app and the I restart it, will the app republish a second time the same articles?
- what does the setting "started": false?
- seems that the app isn't able to check rss feeds from youtube channels, could this feature be improved?

**Comment by ArthurPatriot** [comment]
This app created only for UpWork Feed.

If you restart the app, it doesn't send old messages. Started option
control this.

I'm working for new version. With more features - black/white filters,
example.
